---
- name: personal laptop setup on ubuntu
  hosts: localhost
  connection: local

  vars:
  - home: "{{ansible_env.HOME}}"
  - dropbox_version: 2015.10.28_amd64

  roles:
    - gnome-shell
    - misc
    - dropbox
    - atom-editor
    - ansiblebit.launchpad-ppa-webupd8
    - role: ansiblebit.oracle-java
      ansiblebit.oracle-java:
        oracle_java_set_as_default: yes
    #~ - role: nvm
      #~ nvm:
        #~ version: v0.29.0
        #~ node_version: stable

