---
- apt: update_cache=yes
  become: yes
- name: install misc packages
  apt: name={{item}}
  become: yes
  with_items:
  - ubuntu-restricted-extras
  - keepassx
  - gimp
  - chromium-browser
  # media players
  - clementine
  - vlc
  - gnome-mplayer
  # programming tools
  - git
  - git-cola
  - gitk
  - meld
  - vim
  - scite
  # python
  - ipython
  # c++
  - libtool
  - autoconf
  - automake
  - libboost-all-dev

- name: uninstall totem
  apt: name=totem state=absent
  become: yes
